### ISSUE TITLE
Patching without NPWR

### ISSUE THREAD

**Issue by doggo21** [SilicaAndPina/trophyPatcher#1]
Is there a way to patch the TRP file without the NPWR trophy data? I'm trying to unlock trophies for a game but it won't create the NPWR data. The trophax menu opens in game but it doesn't allow you to maneuver through it. I've tried everything the game doesn't even let you get past the title screen and asks you to connect to the internet and update to 3.67 to get past it. 

Game: MHFG PCSG00350.

**Comment by SilicaAndPina** [comment]
Have you tried spoofing game version / PSN Spoofing

you can sometimes do it from the decrypted eboot.bin however this feature is not implemented in trophyPatcher at this time..

**Comment by doggo21** [comment]
Thanks for the reply. I have tried spoofing to 3.67 and using netcheck bypass but it still prompts for an updated version since the game is online only.

**Comment by SilicaAndPina** [comment]
Oh its the GAME update check? thats pretty easy to get around.

gimmie param.sfo. ill make a patch real quick,

**Comment by SilicaAndPina** [comment]
Feature added in v1.1 :) (make sure you use maidump'ed or vitamin dumped eboot.bin! (only way to decrypt eboot right now.))

**Comment by doggo21** [comment]
changing the APP_VER to 99.99 gives me a C2-10362-2 error

**Comment by SilicaAndPina** [comment]
Use UX0:PATCH. As it bypasses integrity checks

**Comment by doggo21** [comment]
Just wondering... is<!--Sce-Np-Trophy-Signature from TROPCONF.SFM inside TROPHY.TRP the same as NpCommSign?

**Comment by SilicaAndPina** [comment]
Nope that's the "public" key its basicly RSA signed NpCommSign is "private" key  (its checked at Sony's server too so modifying trp is "possible" but useless)
